import { configureStore, createSlice } from "@reduxjs/toolkit";
import authReducer from "../store/reducers/auth.reducers";
import applicationReducer from "./reducers/application.reducers";

// Create a slice with a name, an initial state, and reducer logic
const counterSlice = createSlice({
  name: "counter",
  initialState: { count: 0 },
  reducers: {
    increment: (state) => {
      state.count += 1;
    },
    decrement: (state) => {
      state.count -= 1;
    },
  },
});

// Export the actions generated by createSlice
export const { increment, decrement } = counterSlice.actions;

// Create the Redux store
const store = configureStore({
  reducer: {
    counter: counterSlice.reducer,
    auth: authReducer,
    application: applicationReducer,
  },
});

export default store;
